networks:
  dev:


services:
  web:
    build: .
    container_name: django_app
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - dev

  nginx:
    image: nginx:stable-alphe
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - dev

volumes:
  static_volume:
  media_volume: 