# Generated by Django 4.2.16 on 2025-05-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa_enabled',
        ),
    ]
