# Generated by Django 4.2.16 on 2025-06-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_remove_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_user',
            field=models.ForeignKey(blank=True, default='Guest', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.role'),
        ),
    ]
