# Generated by Django 4.2.16 on 2025-05-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_user_hwid_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_user',
        ),
    ]
