# Generated by Django 4.2.16 on 2025-05-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_userloginhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginHistory',
        ),
    ]
