# Generated by Django 4.2.16 on 2025-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_alter_user_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
