# Generated by Django 4.2.16 on 2025-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
