# Generated by Django 4.2.16 on 2025-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_remove_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='HEX цвет роли (например, #FF0000)', max_length=7),
        ),
    ]
