# Generated by Django 4.2.16 on 2025-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_role_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='surnames',
            field=models.CharField(blank=True, help_text='Список псевдонимов через запятую', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Красный'), ('#00FF00', 'Зеленый'), ('#0000FF', 'Синий'), ('#FFFF00', 'Желтый'), ('#FF00FF', 'Пурпурный'), ('#00FFFF', 'Голубой'), ('#FFFFFF', 'Белый'), ('#000000', 'Черный'), ('#808080', 'Серый'), ('#FFA500', 'Оранжевый'), ('#800080', 'Фиолетовый'), ('#008000', 'Темно-зеленый')], default='#FFFFFF', help_text='Выберите цвет из списка или укажите свой в формате HEX (#FF0000)', max_length=7),
        ),
    ]
