# Generated by Django 4.2.16 on 2025-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_clanmember_surnames_alter_role_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmember',
            name='image',
        ),
    ]
