# Generated by Django 4.2.16 on 2025-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_remove_clanmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'Красный'), ('#00FF00', 'Зеленый'), ('#0000FF', 'Синий'), ('#FFFF00', 'Желтый'), ('#FF00FF', 'Пурпурный'), ('#00FFFF', 'Голубой'), ('#FFFFFF', 'Белый'), ('#000000', 'Черный'), ('#808080', 'Серый'), ('#FFA500', 'Оранжевый'), ('#800080', 'Фиолетовый'), ('#008000', 'Темно-зеленый')], default='#FFFFFF', max_length=7),
        ),
    ]
