# Generated by Django 4.2.16 on 2025-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_role_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmember',
            name='platform',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitch', 'Twitch'), ('twitter', 'Twitter'), ('steam', 'Steam'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('funpay', 'FunPay'), ('guns_lol', 'Guns.lol'), ('fakebio', 'FakeBio'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('other', 'Other Site')], max_length=20),
        ),
    ]
